DROP TABLE IF EXISTS person;
CREATE TABLE person(
ADMIN VARCHAR(15) PRIMARY KEY,
REGISTERED VARCHAR(15) NOT NULL); 

DROP TABLE IF EXISTS admin;
CREATE TABLE admin(
USER_NAME VARCHAR(15) NOT NULL,
ID VARCHAR(15) NOT NULL,
PASSWORD VARCHAR(15) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
TELEPHONE VARCHAR(15)); 

DROP TABLE IF EXISTS registered;
CREATE TABLE registered(
USER_NAME VARCHAR(15) NOT NULL,
ID VARCHAR(15) NOT NULL,
PASSWORD VARCHAR(15) NOT NULL,
EMAIL VARCHAR(45) NOT NULL,
TELEPHONE VARCHAR(15));

DROP TABLE IF EXISTS bookings; 
CREATE TABLE bookings(
NAME VARCHAR(15) NOT NULL,
DESCRIPTION VARCHAR(45) NOT NULL,
OWNER VARCHAR(15) NOT NULL); 

DROP TABLE IF EXISTS rooms;
CREATE TABLE rooms(
LOCATION VARCHAR(15) NOT NULL,
DESCRIPTION VARCHAR(45) NOT NULL,
TYPE VARCHAR(15) NOT NULL,
NAME VARCHAR(15) NOT NULL); 

DROP TABLE IF EXISTS nci;
CREATE TABLE nci(
ID VARCHAR(15) NOT NULL,
CAPACITY VARCHAR(45) NOT NULL); 

DROP TABLE IF EXISTS book;
CREATE TABLE book(
NAME VARCHAR(15) NOT NULL;
DATETIME NOT NULL,
ROOM VARCHAR(10) NOT NULL);





COMMIT;